<?php

namespace Database\Seeders;

use App\Models\SeoMetadata;
use Illuminate\Database\Seeder;

class SeoMetadataSeeder extends Seeder
{
    public function run(): void
    {
        $pages = [
            // === HOMEPAGE ===
            ['url_path' => '/', 'page_title' => 'Homepage', 'meta_title' => 'Fitness Aannemer | Fitnessapparatuur & Complete Gymoplossingen', 'meta_description' => 'Fitness Aannemer ontwerpt, levert en installeert complete fitnessoplossingen op maat. Van boutique gym tot bedrijfsfitness. Topmerken als Life Fitness, Matrix en Concept2.'],

            // === VASTE PAGINAS ===
            ['url_path' => '/gratis-adviesgesprek', 'page_title' => 'Gratis Adviesgesprek', 'meta_title' => 'Gratis Adviesgesprek | Fitness Aannemer', 'meta_description' => 'Plan een gratis adviesgesprek met Fitness Aannemer. Vertel ons over jouw project en wij nemen binnen 24 uur contact op.'],
            ['url_path' => '/over-ons', 'page_title' => 'Over ons', 'meta_title' => 'Over ons | Fitness Aannemer', 'meta_description' => 'Maak kennis met Stijn Harder, oprichter van Fitness Aannemer. Van webshop tot volledige gymbouw. Ontdek ons verhaal, onze aanpak en waarom wij anders zijn.'],
            ['url_path' => '/contact', 'page_title' => 'Contact', 'meta_title' => 'Contact | Fitness Aannemer', 'meta_description' => 'Neem contact op met Fitness Aannemer. Bel, mail of bezoek ons voor advies over jouw fitnessruimte.'],
            ['url_path' => '/offerte-aanvragen', 'page_title' => 'Offerte Aanvragen', 'meta_title' => 'Offerte Aanvragen | Fitness Aannemer', 'meta_description' => 'Vraag een vrijblijvende offerte aan voor jouw fitnessproject. Van sportscholen tot homegyms, wij maken een voorstel op maat.'],
            ['url_path' => '/onze-merken', 'page_title' => 'Onze Merken', 'meta_title' => 'Onze Merken | Fitness Aannemer', 'meta_description' => 'Fitness Aannemer werkt met topmerken als Life Fitness, Matrix, Concept2, KingsBox, Gym80 en Keiser. Ontdek ons assortiment.'],

            // === DIENSTEN ===
            ['url_path' => '/diensten', 'page_title' => 'Diensten', 'meta_title' => 'Onze Diensten | Fitness Aannemer', 'meta_description' => 'Eén partner, alle diensten. Fitness Aannemer verzorgt inrichting, levering, installatie, onderhoud en leasing van fitnessapparatuur.'],
            ['url_path' => '/diensten/inrichting-en-planning', 'page_title' => 'Inrichting & Planning', 'meta_title' => 'Inrichting & Planning | Fitness Aannemer', 'meta_description' => 'Professioneel gymontwerp met 3D visualisatie. Fitness Aannemer maakt een doordacht plan voor jouw fitnessruimte, van plattegrond tot apparatuurkeuze.'],
            ['url_path' => '/diensten/levering-en-installatie', 'page_title' => 'Levering & Installatie', 'meta_title' => 'Levering & Installatie | Fitness Aannemer', 'meta_description' => 'Complete levering en professionele installatie van fitnessapparatuur door ons eigen montageteam. Turnkey oplevering in heel Nederland en Belgie.'],
            ['url_path' => '/diensten/onderhoud-en-reparaties', 'page_title' => 'Onderhoud & Reparaties', 'meta_title' => 'Onderhoud & Reparaties | Fitness Aannemer', 'meta_description' => 'Professioneel onderhoud en snelle reparatie van fitnessapparatuur. Minimaliseer downtime en verleng de levensduur van jouw investering.'],
            ['url_path' => '/diensten/leasing-en-financiering', 'page_title' => 'Leasing & Financiering', 'meta_title' => 'Leasing & Financiering | Fitness Aannemer', 'meta_description' => 'Flexibele lease- en financieringsopties voor fitnessapparatuur. Start direct met topapparatuur en spreid de kosten met operational lease, financial lease of financiering.'],

            // === OPLOSSINGEN ===
            ['url_path' => '/sportschool-inrichten', 'page_title' => 'Sportschool inrichten', 'meta_title' => 'Sportschool inrichten | Fitness Aannemer', 'meta_description' => 'Laat jouw sportschool professioneel inrichten door Fitness Aannemer. Van ontwerp tot installatie, compleet op maat.'],
            ['url_path' => '/pilates-studio-inrichten', 'page_title' => 'Pilates studio inrichten', 'meta_title' => 'Pilates studio inrichten | Fitness Aannemer', 'meta_description' => 'Professionele pilates studio inrichting op maat. Reformers, apparatuur en interieurontwerp door Fitness Aannemer.'],
            ['url_path' => '/pt-studio-inrichten', 'page_title' => 'PT studio inrichten', 'meta_title' => 'PT studio inrichten | Fitness Aannemer', 'meta_description' => 'PT studio inrichting op maat. Exclusieve personal training ruimtes ontworpen en gerealiseerd door Fitness Aannemer.'],
            ['url_path' => '/hotel-gym-inrichten', 'page_title' => 'Hotel gym inrichten', 'meta_title' => 'Hotel gym inrichten | Fitness Aannemer', 'meta_description' => 'Hotel gym inrichting door Fitness Aannemer. Premium fitnessruimtes voor hotels die hun gasten een topervaring willen bieden.'],
            ['url_path' => '/wellnessruimte-inrichten', 'page_title' => 'Wellnessruimte inrichten', 'meta_title' => 'Wellnessruimte inrichten | Fitness Aannemer', 'meta_description' => 'Wellnessruimte inrichting op maat. Recovery, sauna en relaxruimtes ontworpen door Fitness Aannemer.'],
            ['url_path' => '/boksruimte-inrichten', 'page_title' => 'Boksruimte inrichten', 'meta_title' => 'Boksruimte inrichten | Fitness Aannemer', 'meta_description' => 'Boksruimte en MMA ruimte inrichten. Professionele bokszakken, ringen en trainingsapparatuur door Fitness Aannemer.'],
            ['url_path' => '/homegyms-inrichten', 'page_title' => 'Homegym inrichten', 'meta_title' => 'Homegym inrichten | Fitness Aannemer', 'meta_description' => 'Luxe homegym inrichting op maat. Van ontwerp tot installatie, Fitness Aannemer realiseert jouw droomhomegym.'],
            ['url_path' => '/crossfit-box-inrichten', 'page_title' => 'CrossFit box inrichten', 'meta_title' => 'CrossFit box inrichten | Fitness Aannemer', 'meta_description' => 'CrossFit box inrichting op maat. Rigs, racks, bumper plates en functionele apparatuur door Fitness Aannemer.'],
            ['url_path' => '/bedrijfsfitness-inrichten', 'page_title' => 'Bedrijfsfitness inrichten', 'meta_title' => 'Bedrijfsfitness inrichten | Fitness Aannemer', 'meta_description' => 'Bedrijfsfitness inrichting op maat. Creeer een professionele fitnessruimte voor jouw medewerkers met Fitness Aannemer.'],
            ['url_path' => '/hyrox-box-inrichten', 'page_title' => 'Hyrox box inrichten', 'meta_title' => 'Hyrox box inrichten | Fitness Aannemer', 'meta_description' => 'Hyrox trainingsruimte inrichting op maat. SkiErg, roeimachines, sleds en functionele apparatuur door Fitness Aannemer.'],
            ['url_path' => '/recovery-ruimte-inrichten', 'page_title' => 'Recovery ruimte inrichten', 'meta_title' => 'Recovery ruimte inrichten | Fitness Aannemer', 'meta_description' => 'Recovery ruimte inrichting met cold plunge, sauna, massage en meer. Professioneel herstel door Fitness Aannemer.'],
            ['url_path' => '/groepsfitness-ruimte-inrichten', 'page_title' => 'Groepsfitness ruimte inrichten', 'meta_title' => 'Groepsfitness ruimte inrichten | Fitness Aannemer', 'meta_description' => 'Groepsfitness ruimte inrichting op maat. Zalen voor spinning, HIIT, yoga en meer door Fitness Aannemer.'],

            // === PROJECTEN ===
            ['url_path' => '/projecten', 'page_title' => 'Projecten', 'meta_title' => 'Projecten | Fitness Aannemer', 'meta_description' => 'Bekijk onze gerealiseerde projecten. Van PT studio\'s tot commerciele sportscholen. Ontdek wat Fitness Aannemer heeft gerealiseerd.'],
            ['url_path' => '/projecten/pt024-nijmegen', 'page_title' => 'PT024 Nijmegen', 'meta_title' => 'PT024 Nijmegen | Fitness Aannemer', 'meta_description' => 'PT024 Nijmegen: exclusieve personal training studio van 200 m2, volledig ingericht door Fitness Aannemer. Bekijk het resultaat.'],
            ['url_path' => '/projecten/ballin-fit-amsterdam', 'page_title' => 'Ballin Fit Amsterdam', 'meta_title' => 'Ballin Fit Amsterdam | Fitness Aannemer', 'meta_description' => 'Ballin Fit Amsterdam: luxe personal training gym van 598 m2, van casco naar turnkey opgeleverd door Fitness Aannemer.'],
            ['url_path' => '/projecten/vitality-sports-duiven', 'page_title' => 'Vitality Sports Duiven', 'meta_title' => 'Vitality Sports Duiven | Fitness Aannemer', 'meta_description' => 'Vitality Sports Duiven: functionele gym van 1.000 m2, compleet ingericht door Fitness Aannemer. Bekijk het project.'],
            ['url_path' => '/projecten/upshape-gym-den-haag', 'page_title' => 'UpShape Gym Den Haag', 'meta_title' => 'UpShape Gym Den Haag | Fitness Aannemer', 'meta_description' => 'UpShape Gym Den Haag: high-end PT studio van 437 m2, compleet ingericht door Fitness Aannemer. Bekijk het project.'],
            ['url_path' => '/projecten/farm-fit-culemborg', 'page_title' => 'Farm Fit Culemborg', 'meta_title' => 'Farm Fit Culemborg | Fitness Aannemer', 'meta_description' => 'Farm Fit Culemborg: functionele gym van 200 m2, compact maar compleet ingericht door Fitness Aannemer.'],

            // === APPARATUUR ===
            ['url_path' => '/apparatuur', 'page_title' => 'Apparatuur', 'meta_title' => 'Apparatuur | Fitness Aannemer', 'meta_description' => 'Ontdek ons complete assortiment fitnessapparatuur. Cardio, kracht, functioneel, gewichten, flooring en herstel van topmerken.'],
            ['url_path' => '/apparatuur/collecties', 'page_title' => 'Collecties', 'meta_title' => 'Collecties | Fitness Aannemer', 'meta_description' => 'Complete apparatuurcollecties van topmerken. Samengestelde pakketten voor jouw fitnessruimte door Fitness Aannemer.'],
            ['url_path' => '/apparatuur/cardio', 'page_title' => 'Cardio apparatuur', 'meta_title' => 'Cardio apparatuur | Fitness Aannemer', 'meta_description' => 'Premium cardio apparatuur: loopbanden, fietsen, crosstrainers en roeimachines van Life Fitness, Matrix en Concept2.'],
            ['url_path' => '/apparatuur/krachtapparatuur', 'page_title' => 'Krachtapparatuur', 'meta_title' => 'Krachtapparatuur | Fitness Aannemer', 'meta_description' => 'Commerciele krachtapparatuur van Gym80, Life Fitness en Hammer Strength. Pin-loaded, plate-loaded en cable machines.'],
            ['url_path' => '/apparatuur/apparatuur-functioneel', 'page_title' => 'Functionele apparatuur', 'meta_title' => 'Functionele apparatuur | Fitness Aannemer', 'meta_description' => 'Functionele fitnessapparatuur: rigs, racks, kettlebells, battleropes en meer. CrossFit en functional training door Fitness Aannemer.'],
            ['url_path' => '/apparatuur/gewichten', 'page_title' => 'Gewichten', 'meta_title' => 'Gewichten | Fitness Aannemer', 'meta_description' => 'Professionele dumbbells, barbells, bumper plates en gewichtsopslag. Competition-grade en commercieel door Fitness Aannemer.'],
            ['url_path' => '/apparatuur/flooring', 'page_title' => 'Flooring', 'meta_title' => 'Flooring | Fitness Aannemer', 'meta_description' => 'Professionele gymvloeren op maat. Rubber flooring, kunstgras, tatami en meer. Geleverd en gelegd door Fitness Aannemer.'],
            ['url_path' => '/apparatuur/herstel', 'page_title' => 'Herstelapparatuur', 'meta_title' => 'Herstelapparatuur | Fitness Aannemer', 'meta_description' => 'Recovery en herstelapparatuur: cold plunge, sauna, compressietherapie en massage-equipment. Door Fitness Aannemer.'],

            // === FITNESSWIJZER ===
            ['url_path' => '/fitnesswijzer', 'page_title' => 'Fitnesswijzer', 'meta_title' => 'Fitnesswijzer | Fitness Aannemer', 'meta_description' => 'De Fitnesswijzer van Fitness Aannemer. Tips, inspiratie, verdienmodellen en gymreviews voor iedereen die een fitnessruimte wil starten of verbeteren.'],
            ['url_path' => '/fitnesswijzer/gym-verdienmodellen', 'page_title' => 'Gym Verdienmodellen', 'meta_title' => 'Gym Verdienmodellen | Fitnesswijzer | Fitness Aannemer', 'meta_description' => 'Ontdek de verschillende verdienmodellen voor sportscholen en fitnessruimtes. Van leasekosten tot winstberekeningen en slimme verdienstrategieen.'],
            ['url_path' => '/fitnesswijzer/tips-en-inspiratie', 'page_title' => 'Tips & Inspiratie', 'meta_title' => 'Tips & Inspiratie | Fitnesswijzer | Fitness Aannemer', 'meta_description' => 'Praktische tips en inspiratie voor het inrichten en runnen van jouw fitnessruimte. Van apparatuurkeuze tot gym design en financiering.'],
            ['url_path' => '/fitnesswijzer/gymreviews', 'page_title' => 'Gymreviews', 'meta_title' => 'Gymreviews | Fitnesswijzer | Fitness Aannemer', 'meta_description' => 'Uitgebreide gymreviews van de meest bijzondere sportscholen en fitnessruimtes van Nederland. Apparatuur, sfeer, prijs en faciliteiten beoordeeld.'],

            // === VERDIENMODELLEN ===
            ['url_path' => '/fitnesswijzer/gym-verdienmodellen/eigen-gym-starten', 'page_title' => 'Eigen gym starten voor 2000 per maand', 'meta_title' => 'Een complete gym starten voor 2.000 euro per maand | Fitness Aannemer', 'meta_description' => 'Ontdek hoe je een eigen gym kunt starten door apparatuur te leasen vanaf 2.000 euro per maand. Leasekosten, verdienmodel en praktische tips.'],
            ['url_path' => '/fitnesswijzer/gym-verdienmodellen/boutique-gym-starten', 'page_title' => 'Boutique gym starten', 'meta_title' => 'Boutique gym starten: leasekosten en verdienmodel | Fitness Aannemer', 'meta_description' => 'Wat kost het om een boutique gym te starten? Leasekosten, verdienmodel en praktische tips voor een premium fitnessruimte.'],
            ['url_path' => '/fitnesswijzer/gym-verdienmodellen/wat-kost-een-sportschool-per-maand', 'page_title' => 'Wat kost een sportschool per maand', 'meta_title' => 'Wat kost een sportschool per maand? | Fitness Aannemer', 'meta_description' => 'Complete kostenoverzicht van een sportschool. Huur, personeel, apparatuur-lease, verzekeringen en vaste lasten op een rij.'],
            ['url_path' => '/fitnesswijzer/gym-verdienmodellen/wat-verdient-een-sportschoolhouder', 'page_title' => 'Wat verdient een sportschoolhouder', 'meta_title' => 'Wat verdient een sportschoolhouder? | Fitness Aannemer', 'meta_description' => 'Hoeveel verdient een sportschoolhouder? Realistisch verdienmodel met omzet, kosten en netto winst berekening.'],
            ['url_path' => '/fitnesswijzer/gym-verdienmodellen/hyrox-studio-starten-kosten-en-verdienmodel', 'page_title' => 'HYROX studio starten', 'meta_title' => 'HYROX studio starten: kosten en verdienmodel | Fitness Aannemer', 'meta_description' => 'Wat kost het om een HYROX studio te starten? Investering, apparatuur, leasekosten en verdienmodel op een rij.'],
            ['url_path' => '/fitnesswijzer/gym-verdienmodellen/fitnessapparatuur-leasen', 'page_title' => 'Fitnessapparatuur leasen', 'meta_title' => 'Fitnessapparatuur leasen, zo werkt het | Fitness Aannemer', 'meta_description' => 'Alles over het leasen van fitnessapparatuur. Kosten, looptijden, voordelen en hoe je een lease-aanvraag doet.'],
            ['url_path' => '/fitnesswijzer/gym-verdienmodellen/dit-kost-het-bouwen-van-een-pilates-studio', 'page_title' => 'Pilates studio kosten', 'meta_title' => 'Dit kost het bouwen van een pilates studio | Fitness Aannemer', 'meta_description' => 'Wat kost het om een pilates studio te bouwen? Reformers, inrichting, huur en verdienmodel. Een compleet kostenoverzicht.'],
            ['url_path' => '/fitnesswijzer/gym-verdienmodellen/verdriedubbel-je-omzet-met-een-slimme-fitnessinvestering', 'page_title' => 'Verdriedubbel je omzet', 'meta_title' => 'Verdriedubbel je omzet met een slimme fitnessinvestering | Fitness Aannemer', 'meta_description' => 'Hoe een doordachte investering in fitnessapparatuur je omzet kan verdriedubbelen. ROI, upselling en slimme uitbreiding.'],
            ['url_path' => '/fitnesswijzer/gym-verdienmodellen/zoveel-verdienen-gyms-aan-goede-voornemens', 'page_title' => 'Gyms en goede voornemens', 'meta_title' => 'Zoveel verdienen gyms aan goede voornemens | Fitness Aannemer', 'meta_description' => 'Hoeveel extra omzet genereren sportscholen in januari? De impact van goede voornemens op je gym-omzet en hoe je ervan profiteert.'],
            ['url_path' => '/fitnesswijzer/gym-verdienmodellen/zo-verdienen-gyms-aan-trainingsschemas-fitnessaannemer', 'page_title' => 'Gyms en trainingsschemas', 'meta_title' => 'Zo verdienen gyms aan trainingsschema\'s | Fitness Aannemer', 'meta_description' => 'Hoe sportscholen extra omzet genereren met gepersonaliseerde trainingsschema\'s. 3.000 euro extra per maand met 30% uptake.'],
            ['url_path' => '/fitnesswijzer/gym-verdienmodellen/het-verdienmodel-concept-van-sportcity', 'page_title' => 'SportCity verdienmodel', 'meta_title' => 'Het verdienmodel achter het vriend-meenemen concept van SportCity | Fitness Aannemer', 'meta_description' => 'Hoe het vriend-meenemen concept van SportCity werkt als verdienmodel. Referral marketing, retentie en omzetgroei voor sportscholen.'],

            // === TIPS & INSPIRATIE ===
            ['url_path' => '/fitnesswijzer/tips-en-inspiratie/waar-haal-je-het-geld-vandaan-om-een-gym-te-starten', 'page_title' => 'Gym financieren', 'meta_title' => 'Gym starten financieren: dit zijn je opties | Fitness Aannemer', 'meta_description' => 'Ontdek hoe je een gym kunt financieren zonder alles zelf te betalen. Investeerders, bankkrediet en het leasen van apparatuur.'],
            ['url_path' => '/fitnesswijzer/tips-en-inspiratie/gym-inrichten-tips', 'page_title' => 'Gym inrichten tips', 'meta_title' => 'Gym inrichten? Dit moet je weten | Fitness Aannemer', 'meta_description' => 'Ontdek wat er echt toe doet bij het inrichten van een gym: routing, looplijnen, veiligheidsruimte en beleving.'],
            ['url_path' => '/fitnesswijzer/tips-en-inspiratie/airco-in-gym-luxe-of-noodzakelijk', 'page_title' => 'Airco in de gym', 'meta_title' => 'Airco in de gym: luxe of noodzakelijk? | Fitness Aannemer', 'meta_description' => 'Waarom airco in je gym geen luxe is maar een slimme investering in comfort, veiligheid en retentie. Praktische tips.'],
            ['url_path' => '/fitnesswijzer/tips-en-inspiratie/partytent-naar-gym-600m2', 'page_title' => 'Van partytent naar gym', 'meta_title' => 'Van partytent naar gym van 600 m2 | Fitness Aannemer', 'meta_description' => 'Van een partytent naar een gym van 600 m2. Ontdek hoe deze ondernemer slim is gegroeid met visie en een goed plan.'],
            ['url_path' => '/fitnesswijzer/tips-en-inspiratie/de-grootste-gym-die-wij-tot-nu-toe-hebben-gebouwd', 'page_title' => 'Grootste gym gebouwd', 'meta_title' => 'De grootste gym die wij tot nu toe hebben gebouwd | Fitness Aannemer', 'meta_description' => 'Ontdek de investering, ledenaantallen en winst van de grootste gym die we tot nu toe hebben gebouwd. 1.000 m2 fitnesscase.'],
            ['url_path' => '/fitnesswijzer/tips-en-inspiratie/de-meest-winstgevende-gymconcepten-van-dit-moment', 'page_title' => 'Winstgevende gymconcepten', 'meta_title' => 'De meest winstgevende gymconcepten van dit moment | Fitness Aannemer', 'meta_description' => 'Ontdek welke fitnessconcepten het meest winstgevend zijn en hoe jij met de juiste strategie een succesvolle gym opbouwt.'],
            ['url_path' => '/fitnesswijzer/tips-en-inspiratie/meerdere-pilatesstudios-openen-met-een-slim-concept', 'page_title' => 'Meerdere pilatesstudios openen', 'meta_title' => 'Meerdere pilatesstudio\'s openen met een slim concept | Fitness Aannemer', 'meta_description' => 'Ontdek waarom het slimmer is om meerdere pilatesstudio\'s tegelijk te openen met een schaalbaar concept.'],
            ['url_path' => '/fitnesswijzer/tips-en-inspiratie/een-eigen-gym-openen-van-idee-tot-opening', 'page_title' => 'Eigen gym openen', 'meta_title' => 'Een eigen gym openen: van idee tot opening | Fitness Aannemer', 'meta_description' => 'Stap voor stap je eigen gym openen. Van concept en locatie tot 3D-ontwerp, lease en opening, vanaf een investering van 40.000 euro.'],
            ['url_path' => '/fitnesswijzer/tips-en-inspiratie/zo-krijg-je-sneller-een-vergunning-voor-jouw-sportschool', 'page_title' => 'Sportschool vergunning', 'meta_title' => 'Zo krijg je sneller een vergunning voor jouw sportschool | Fitness Aannemer', 'meta_description' => 'Voorkom vertraging bij de gemeente met deze praktische tips voor het aanvragen van een sportschoolvergunning.'],
            ['url_path' => '/fitnesswijzer/tips-en-inspiratie/sportschool-opzetten', 'page_title' => 'Sportschool opzetten', 'meta_title' => 'Sportschool opzetten: stappen van idee tot opening | Fitness Aannemer', 'meta_description' => 'Welke stappen doorloop je bij het opzetten van een sportschool? Van kennismaking en ontwerp tot oplevering en nazorg.'],
            ['url_path' => '/fitnesswijzer/tips-en-inspiratie/verlichting-in-je-sportschool-tips', 'page_title' => 'Verlichting sportschool', 'meta_title' => 'Verlichting in je sportschool: tips voor sfeer en beleving | Fitness Aannemer', 'meta_description' => 'Ontdek waar je op moet letten bij het verlichten van je sportschool. Hoe licht sfeer, beleving en uitstraling bepaalt.'],
            ['url_path' => '/fitnesswijzer/tips-en-inspiratie/een-pilatesstudio-openen-in-2025', 'page_title' => 'Pilatesstudio openen', 'meta_title' => 'Pilatesstudio opzetten: van idee tot realisatie inclusief kosten | Fitness Aannemer', 'meta_description' => 'Start jouw pilatesstudio met een duidelijk plan. Ontdek het proces, de kosten en mogelijkheden voor leasing en realisatie.'],
            ['url_path' => '/fitnesswijzer/tips-en-inspiratie/ervaring-met-een-sportschool-laten-bouwen', 'page_title' => 'Sportschool laten bouwen', 'meta_title' => 'Sportschool bouwen: zo verloopt het traject in de praktijk | Fitness Aannemer', 'meta_description' => 'Bekijk hoe een sportschool laten bouwen echt gaat. Van eerste contact tot oplevering inclusief leerpunten.'],
            ['url_path' => '/fitnesswijzer/tips-en-inspiratie/de-grootste-fitnessbeurs-ter-wereld-dit-heb-je-gemist', 'page_title' => 'Grootste fitnessbeurs', 'meta_title' => 'Grootste fitnessbeurs ter wereld: trends, apparatuur en wellness | Fitness Aannemer', 'meta_description' => 'Dit heb je gemist op de grootste fitnessbeurs ter wereld. Trends in apparatuur, wellness, HYROX en de explosie van pilates.'],

            // === GYMREVIEWS ===
            ['url_path' => '/fitnesswijzer/gymreviews/gymreview-aerofitt-duiven', 'page_title' => 'AeroFitt Duiven', 'meta_title' => 'Gymreview: AeroFitt Duiven | Fitness Aannemer', 'meta_description' => 'Review van AeroFitt Duiven: complete sportschool met zwembad, wellness, groepslessen en een machinepark van Matrix. Prijs, sfeer en faciliteiten.'],
            ['url_path' => '/fitnesswijzer/gymreviews/gymreview-cardio-fitness-beverwijk', 'page_title' => 'Cardio Fitness Beverwijk', 'meta_title' => 'Gymreview: Cardio Fitness Beverwijk | Fitness Aannemer', 'meta_description' => 'Review van Cardio Fitness Beverwijk: 37 pin-loaded machines, 64 cardio-apparaten, bokshal en posing room. Groot, betaalbaar en compleet.'],
            ['url_path' => '/fitnesswijzer/gymreviews/gymreview-holyfit-holypadel-arnhem-fitness-aannemer', 'page_title' => 'HolyFit Arnhem', 'meta_title' => 'Gymreview: HolyFit & Holypadel Arnhem | Fitness Aannemer', 'meta_description' => 'Review van HolyFit & Holypadel Arnhem: fitness in een omgebouwde kerk met glas-in-lood ramen, padelbanen en een unieke sfeer.'],
            ['url_path' => '/fitnesswijzer/gymreviews/gymreview-trainmore-black-label', 'page_title' => 'TrainMore Black Label', 'meta_title' => 'Gymreview: TrainMore Black Label | Fitness Aannemer', 'meta_description' => 'Review van TrainMore Black Label Amsterdam: premium fitness met Life Fitness en Hammer Strength, raw industrial design.'],
            ['url_path' => '/fitnesswijzer/gymreviews/gymreview-credo-gym-haarlem', 'page_title' => 'Credo Gym Haarlem', 'meta_title' => 'Gymreview: Credo Gym Haarlem | Fitness Aannemer', 'meta_description' => 'Review van Credo Gym Haarlem: exclusieve apparatuur van Atlantis en Cybex, bodybuilding focus, 24/7 open en sterke branding.'],
            ['url_path' => '/fitnesswijzer/gymreviews/gymreview-r-gym-beverwijk', 'page_title' => 'R-gym Beverwijk', 'meta_title' => 'Gymreview: R-gym Beverwijk | Fitness Aannemer', 'meta_description' => 'Review van R-gym Beverwijk: 3.000m2 met exclusieve Gym80 apparatuur, booty room, Hyrox area en 6-8 groepslessen per dag.'],
            ['url_path' => '/fitnesswijzer/gymreviews/gymreview-xxl-nutrition-gym', 'page_title' => 'XXL Nutrition Gym', 'meta_title' => 'Gymreview: XXL Nutrition Gym | Fitness Aannemer', 'meta_description' => 'Review van de XXL Nutrition Gym: corporate bedrijfsfitness op 150m2 met TechnoGym en Hammer Strength.'],
            ['url_path' => '/fitnesswijzer/gymreviews/gymreview-black-phantom-huizen', 'page_title' => 'Black Phantom Huizen', 'meta_title' => 'Gymreview: Black Phantom Huizen | Fitness Aannemer', 'meta_description' => 'Review van Black Phantom Huizen: underground gym met dark industrial design, geautomatiseerde verlichting en nightclub op weekendavonden.'],
            ['url_path' => '/fitnesswijzer/gymreviews/gymreview-saint-stars-in-amsterdam-fitness-aannemer', 'page_title' => 'Saint & Stars Amsterdam', 'meta_title' => 'Gymreview: Saint & Stars Amsterdam | Fitness Aannemer', 'meta_description' => 'Review van Saint & Stars Amsterdam: ultra-premium fitness in een omgebouwde kerk met gouden halterstangen en luxe afwerking.'],
            ['url_path' => '/fitnesswijzer/gymreviews/healthclub-heijenoord-arnhem-review', 'page_title' => 'Healthclub Heijenoord Arnhem', 'meta_title' => 'Gymreview: Healthclub Heijenoord Arnhem | Fitness Aannemer', 'meta_description' => 'Review van Healthclub Heijenoord Arnhem: de grootste sportschool van Arnhem met eGym, HIIT, dojo, yoga, spinning, boksen en CrossFit.'],
            ['url_path' => '/fitnesswijzer/gymreviews/upshape-review-een-personal-training-studio-waar-alleen-een-op-een-wordt-getraind', 'page_title' => 'UpShape PT Studio', 'meta_title' => 'UpShape review: personal training studio zonder ruis | Fitness Aannemer', 'meta_description' => 'UpShape is een personal training studio waar alleen een-op-een wordt getraind. Review van het concept, apparatuur en verdienmodel.'],
            ['url_path' => '/fitnesswijzer/gymreviews/pilates-studio-openen-zo-deed-club-confidence-het', 'page_title' => 'Club Confidence Pilates', 'meta_title' => 'Pilates studio openen: zo deed Club Confidence het | Fitness Aannemer', 'meta_description' => 'Hoe open je een pilates studio? Bekijk het proces van Club Confidence van ontwerp tot oplevering en ontdek welk budget je nodig hebt.'],

            // === JURIDISCH ===
            ['url_path' => '/privacybeleid', 'page_title' => 'Privacybeleid', 'meta_title' => 'Privacybeleid | Fitness Aannemer', 'meta_description' => 'Lees het privacybeleid van Fitness Aannemer. Hoe wij omgaan met jouw persoonsgegevens, welke data wij verzamelen en jouw rechten.', 'robots' => 'noindex, follow'],
            ['url_path' => '/algemene-voorwaarden', 'page_title' => 'Algemene Voorwaarden', 'meta_title' => 'Algemene Voorwaarden | Fitness Aannemer', 'meta_description' => 'Lees de algemene voorwaarden van Fitness Aannemer. Voorwaarden voor onze diensten, leveringen, garantie en aansprakelijkheid.', 'robots' => 'noindex, follow'],
            ['url_path' => '/cookies', 'page_title' => 'Cookiebeleid', 'meta_title' => 'Cookiebeleid | Fitness Aannemer', 'meta_description' => 'Lees het cookiebeleid van Fitness Aannemer. Welke cookies wij gebruiken, waarom, en hoe je ze kunt beheren.', 'robots' => 'noindex, follow'],
        ];

        foreach ($pages as $page) {
            SeoMetadata::updateOrCreate(
                ['url_path' => $page['url_path']],
                array_merge([
                    'robots' => 'index, follow',
                    'og_type' => 'website',
                ], $page)
            );
        }
    }
}
